// This file generated by LgiRes

#define IDM_MENU_500							500
#define IDM_OPEN								501
#define IDM_TOOLS								502
#define IDM_DUMP								503
#define IDM_RECOVER								504
#define IDM_CLOSE								505
#define IDM_MENU_506							506
#define IDM_EXIT								507
