#include "resdefs.h"
#include "ScribeScripts.h"

//
// Delete duplicate messages recursively through folders.
//

function DeleteDuplicateMessages(App, folder)
{
	Folder = folder;
	if (Folder && Folder.ItemType == ScribeItemMail)
	{
		Msgs = New("HashTable");
		Dupes = New("List");
		Len = Folder.Length;

		for (i=0; i<Len; i++)
		{
			t = Folder.Item[i];
			if (t)
			{
				Id = t.MessageID.Strip("<>");
				if (Id != NULL)
				{
					Existing = Msgs[Id];
					if (Existing)
					{
						Print("Duplicate: " + folder.path + ":" + t.Subject + "\n");
						// Decide which email is older
						if (t.DateReceived < Existing.DateReceived)
						{
							// t is earlier, t replaces existing item
							Dupes[-1] = Existing;
							Msgs[Id] = t;
						}
						else
						{
							// existing is earlier, delete t
							Dupes[-1] = t;
						}
					}
					else
					{
						Msgs[Id] = t;
					}
				}
				else Print("No msgid at " + i + "\n");
			}
			else Print("No item at " + i + "\n");
		}

		if (Dupes.Length > 0)
		{
			if (MessageDlg(App, Sprintf(LoadString(1013), Dupes.Length), App.Name, 4) == 6)
			{
				for (i=0; i<Dupes.Length; i++)
				{
					DeleteThing(Dupes[i]);
				}
			}
		}
	}
}

function DeleteDuplicatesFromFolder(App, Folder)
{
    DeleteDuplicateMessages(App, Folder);
    for (c = Folder.Child; c; c = c.Next)
    {
        DeleteDuplicatesFromFolder(App, c);
    }
}

function RecurseDeleteDuplicatesFromFolder(App, MenuId)
{
    Print("Recursively delete duplicate messages from: " + App.CurrentFolder.Path + " (see console)\n");
    DeleteDuplicatesFromFolder(App, App.CurrentFolder);
    Print("done.\n");
}

function Main(App)
{
	if (!AddToolsMenuItem(LoadString(IDS_REMOVE_DUPES), "RecurseDeleteDuplicatesFromFolder"))
		MessageDlg(App, "Couldn't add hook for Delete Duplicate Messages");
	return 1;
}
