#include "ScribeScripts.h"

function ExtractMailList(Thing)
{
	ListId = Thing.InternetHeader["List-Id"];
	if (!ListId)
	{
		ListOwner = Thing.InternetHeader["List-Owner"];
		if (ListOwner != NULL)
		{
			ListId = ListOwner.Strip("<>");
			if (ListId.Find("mailto:") == 0)
			{
				p = ListId.SplitDelimit(":+@");
				// Print("p="+p+"\n");
				if (p.Length() > 1)
				{
					ListId = p[1];
				}
			}
		}
	}
	
	if (!ListId)
		return ListId;
	if (ListId.Length)
		ListId = ListId.Strip("<>");
	// Print("ListId='"+ListId+"'\n");
	return ListId;
}

function CreateMailingListFilter(App, Thing, CallbackId)
{
	ListId = ExtractMailList(Thing);
	Folder = BrowseFolder(App, "Select folder to filter mailing list into:", ListId);
	if (Folder.Length)
	{
		Filter = CreateThing(ScribeItemFilter);
		Filter.Name = ListId;
		Filter.ConditionsXml = "<Conditions><And><Condition Not='0' Field='mail.InternetHeader[List-Id]' Op='Contains' Value='"+ListId+"'/></And></Conditions>";
		Filter.ActionsXml = "<Actions><Action Type='7' Arg1='false,notnew' /><Action Type='0' Arg1='"+Folder+"'/></Actions>";
		ShowThingWindow(Filter);
	}
}

function CreateFromFilter(App, Thing, CallbackId)
{
	Email = Thing.From.Email;
	Filter = CreateThing(ScribeItemFilter);
	Filter.Name = Email;
	Filter.ConditionsXml = "<Conditions><And><Condition Not='0' Field='mail.From.Email' Op='Contains' Value='"+Email+"'/></And></Conditions>";
	ShowThingWindow(Filter);
}

function GetSortedFilters()
{
	Items = New("List");
	Folders = GetSourceFolders(6);
	for (f=0; f<Folders.length; f++)
	{
		Fld = Folders[f];
		Count = Fld.Item.Length;
		for (i = 0; i < Count; i++)
		{
			Items.Add(Fld.Item[i]);
		}
	}
	Items.Sort("Index");
	return Items;
}

function GetAllGroups()
{
	Items = New("List");
	Folders = GetSourceFolders(SystemFolderGroups);
	for (f=0; f<Folders.length; f++)
	{
		Groups = Folders[f];
		for (i = 0; grp = Groups.Item[i]; i++)
		{
			Items.Add(grp);
		}
	}

	if (Items.Length)
	{
		Items.Sort("-UsedTs");
	}
	else
	{
		Print("GetAllGroups: No groups folder.\n");
	}
	
	return Items;
}

function AddFromToFilter(App, Thing, CallbackId)
{
	Items = GetSortedFilters();
	Filter = Items[CallbackId - 4000];
	if (Filter)
	{
		MailFrom = Thing.From.Email;
		Filter.AddCondition("Mail.From.Email", "=", MailFrom);
	}
	else
	{
		Print("Error: No filter for ID: " + CallbackId + "\n");
	}
}

function AddFromToGroup(App, Thing, CallbackId)
{
	Items = GetAllGroups();
	Group = Items[CallbackId - 5000];
	if (Group)
	{
		Group.AddAddress(Thing.From.Email);
	}
	else
	{
		Print("Error: No group for ID: " + CallbackId + "\n");
	}
}

function CreateFilterMenu(App, Thing, Menu)
{
	if (Thing.Type != ScribeItemMail)
	{
		// This isn't an error...
		return false;
	}

	Sub = MenuAddSubmenu(Menu, "&Create Filter", Menu.Length - 2);
	if (!Sub)
	{
		Print("CreateFilterMenu.Error: MenuAddSubmenu failed.\n");
		return false;
	}

	ListId = ExtractMailList(Thing);
	if (ListId != NULL)
	{
		if (ListId.Length)
		{
			MenuAddItem(Sub, -1, "New filter for email from mailing list '" + ListId + "'", -1, "CreateMailingListFilter", 3000);
		}
		else Print("ListId has no length\n");
	}

	MailFrom = Thing.From.Email;

	MenuAddItem(Sub, -1, "New filter for email from '" + MailFrom + "'", -1, "CreateFromFilter", 3001);
	Sm = MenuAddSubmenu(Sub, "Add '" + MailFrom + "' to existing filter", -1);
	if (Sm)
	{
		Items = GetSortedFilters();
		for (i = 0; i < Items.Length; i++)
		{
			f = Items[i];		
			Txt = "(" + f.Index + ") " + f.Name;			
			MenuAddItem(Sm, -1, Txt, -1, "AddFromToFilter", 4000 + i);
		}
	}
	else Print("CreateFilterMenu: MenuAddSubmenu failed\n");

	Sm2 = MenuAddSubmenu(Sub, "Add '" + MailFrom + "' to contact group", -1);
	if (Sm2)
	{
		Items = GetAllGroups();
		for (i = 0; i < Items.Length; i++)
		{
			grp = Items[i];			
			Str = grp.Name;
			MenuAddItem(Sm2, -1, Str, -1, "AddFromToGroup", 5000 + i);
		}
	}
	else Print("CreateFilterMenu: MenuAddSubmenu failed\n");

	return true;
}

function Main(App)
{
	if (!AddCallback("OnThingContextMenu", "CreateFilterMenu"))
		MessageDlg(App, "Couldn't add CreateFilterMenu");

	return 1;
}
