// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Scribe.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Scribe_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Scribe_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Scribe_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Scribe_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Scribe_2eproto;
namespace scribe {
class Address;
class AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Email;
class EmailDefaultTypeInternal;
extern EmailDefaultTypeInternal _Email_default_instance_;
class Field;
class FieldDefaultTypeInternal;
extern FieldDefaultTypeInternal _Field_default_instance_;
class Folder;
class FolderDefaultTypeInternal;
extern FolderDefaultTypeInternal _Folder_default_instance_;
}  // namespace scribe
PROTOBUF_NAMESPACE_OPEN
template<> ::scribe::Address* Arena::CreateMaybeMessage<::scribe::Address>(Arena*);
template<> ::scribe::Email* Arena::CreateMaybeMessage<::scribe::Email>(Arena*);
template<> ::scribe::Field* Arena::CreateMaybeMessage<::scribe::Field>(Arena*);
template<> ::scribe::Folder* Arena::CreateMaybeMessage<::scribe::Folder>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace scribe {

// ===================================================================

class Field :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:scribe.Field) */ {
 public:
  Field();
  virtual ~Field();

  Field(const Field& from);
  Field(Field&& from) noexcept
    : Field() {
    *this = ::std::move(from);
  }

  inline Field& operator=(const Field& from) {
    CopyFrom(from);
    return *this;
  }
  inline Field& operator=(Field&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Field& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Field* internal_default_instance() {
    return reinterpret_cast<const Field*>(
               &_Field_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Field& a, Field& b) {
    a.Swap(&b);
  }
  inline void Swap(Field* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Field* New() const final {
    return CreateMaybeMessage<Field>(nullptr);
  }

  Field* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Field>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Field& from);
  void MergeFrom(const Field& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Field* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "scribe.Field";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Scribe_2eproto);
    return ::descriptor_table_Scribe_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kWidthFieldNumber = 2,
  };
  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 width = 2;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::int32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:scribe.Field)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Scribe_2eproto;
};
// -------------------------------------------------------------------

class Address :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:scribe.Address) */ {
 public:
  Address();
  virtual ~Address();

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Address& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Address* New() const final {
    return CreateMaybeMessage<Address>(nullptr);
  }

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Address& from);
  void MergeFrom(const Address& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "scribe.Address";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Scribe_2eproto);
    return ::descriptor_table_Scribe_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kEmailFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // string email = 2;
  void clear_email();
  const std::string& email() const;
  void set_email(const std::string& value);
  void set_email(std::string&& value);
  void set_email(const char* value);
  void set_email(const char* value, size_t size);
  std::string* mutable_email();
  std::string* release_email();
  void set_allocated_email(std::string* email);

  // @@protoc_insertion_point(class_scope:scribe.Address)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Scribe_2eproto;
};
// -------------------------------------------------------------------

class Email :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:scribe.Email) */ {
 public:
  Email();
  virtual ~Email();

  Email(const Email& from);
  Email(Email&& from) noexcept
    : Email() {
    *this = ::std::move(from);
  }

  inline Email& operator=(const Email& from) {
    CopyFrom(from);
    return *this;
  }
  inline Email& operator=(Email&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Email& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Email* internal_default_instance() {
    return reinterpret_cast<const Email*>(
               &_Email_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Email& a, Email& b) {
    a.Swap(&b);
  }
  inline void Swap(Email* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Email* New() const final {
    return CreateMaybeMessage<Email>(nullptr);
  }

  Email* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Email>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Email& from);
  void MergeFrom(const Email& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Email* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "scribe.Email";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Scribe_2eproto);
    return ::descriptor_table_Scribe_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kToFieldNumber = 10,
    kLabelFieldNumber = 6,
    kSubjectFieldNumber = 7,
    kFileNameFieldNumber = 13,
    kStructureFieldNumber = 15,
    kMessageIdFieldNumber = 16,
    kFromFieldNumber = 8,
    kReplyFieldNumber = 9,
    kUidFieldNumber = 1,
    kRemoteFlagsFieldNumber = 2,
    kDateSentFieldNumber = 4,
    kDateReceivedFieldNumber = 5,
    kLocalFlagsFieldNumber = 3,
    kColourFieldNumber = 11,
    kSizeFieldNumber = 12,
    kPriorityFieldNumber = 14,
  };
  // repeated .scribe.Address to = 10;
  int to_size() const;
  void clear_to();
  ::scribe::Address* mutable_to(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Address >*
      mutable_to();
  const ::scribe::Address& to(int index) const;
  ::scribe::Address* add_to();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Address >&
      to() const;

  // string label = 6;
  void clear_label();
  const std::string& label() const;
  void set_label(const std::string& value);
  void set_label(std::string&& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  std::string* mutable_label();
  std::string* release_label();
  void set_allocated_label(std::string* label);

  // string subject = 7;
  void clear_subject();
  const std::string& subject() const;
  void set_subject(const std::string& value);
  void set_subject(std::string&& value);
  void set_subject(const char* value);
  void set_subject(const char* value, size_t size);
  std::string* mutable_subject();
  std::string* release_subject();
  void set_allocated_subject(std::string* subject);

  // string fileName = 13;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);

  // string structure = 15;
  void clear_structure();
  const std::string& structure() const;
  void set_structure(const std::string& value);
  void set_structure(std::string&& value);
  void set_structure(const char* value);
  void set_structure(const char* value, size_t size);
  std::string* mutable_structure();
  std::string* release_structure();
  void set_allocated_structure(std::string* structure);

  // string messageId = 16;
  void clear_messageid();
  const std::string& messageid() const;
  void set_messageid(const std::string& value);
  void set_messageid(std::string&& value);
  void set_messageid(const char* value);
  void set_messageid(const char* value, size_t size);
  std::string* mutable_messageid();
  std::string* release_messageid();
  void set_allocated_messageid(std::string* messageid);

  // .scribe.Address from = 8;
  bool has_from() const;
  void clear_from();
  const ::scribe::Address& from() const;
  ::scribe::Address* release_from();
  ::scribe::Address* mutable_from();
  void set_allocated_from(::scribe::Address* from);

  // .scribe.Address reply = 9;
  bool has_reply() const;
  void clear_reply();
  const ::scribe::Address& reply() const;
  ::scribe::Address* release_reply();
  ::scribe::Address* mutable_reply();
  void set_allocated_reply(::scribe::Address* reply);

  // uint32 uid = 1;
  void clear_uid();
  ::PROTOBUF_NAMESPACE_ID::uint32 uid() const;
  void set_uid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // int32 remoteFlags = 2;
  void clear_remoteflags();
  ::PROTOBUF_NAMESPACE_ID::int32 remoteflags() const;
  void set_remoteflags(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 dateSent = 4;
  void clear_datesent();
  ::PROTOBUF_NAMESPACE_ID::int64 datesent() const;
  void set_datesent(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 dateReceived = 5;
  void clear_datereceived();
  ::PROTOBUF_NAMESPACE_ID::int64 datereceived() const;
  void set_datereceived(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 localFlags = 3;
  void clear_localflags();
  ::PROTOBUF_NAMESPACE_ID::int32 localflags() const;
  void set_localflags(::PROTOBUF_NAMESPACE_ID::int32 value);

  // uint32 colour = 11;
  void clear_colour();
  ::PROTOBUF_NAMESPACE_ID::uint32 colour() const;
  void set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // int64 size = 12;
  void clear_size();
  ::PROTOBUF_NAMESPACE_ID::int64 size() const;
  void set_size(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 priority = 14;
  void clear_priority();
  ::PROTOBUF_NAMESPACE_ID::int32 priority() const;
  void set_priority(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:scribe.Email)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Address > to_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr subject_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr structure_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr messageid_;
  ::scribe::Address* from_;
  ::scribe::Address* reply_;
  ::PROTOBUF_NAMESPACE_ID::uint32 uid_;
  ::PROTOBUF_NAMESPACE_ID::int32 remoteflags_;
  ::PROTOBUF_NAMESPACE_ID::int64 datesent_;
  ::PROTOBUF_NAMESPACE_ID::int64 datereceived_;
  ::PROTOBUF_NAMESPACE_ID::int32 localflags_;
  ::PROTOBUF_NAMESPACE_ID::uint32 colour_;
  ::PROTOBUF_NAMESPACE_ID::int64 size_;
  ::PROTOBUF_NAMESPACE_ID::int32 priority_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Scribe_2eproto;
};
// -------------------------------------------------------------------

class Folder :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:scribe.Folder) */ {
 public:
  Folder();
  virtual ~Folder();

  Folder(const Folder& from);
  Folder(Folder&& from) noexcept
    : Folder() {
    *this = ::std::move(from);
  }

  inline Folder& operator=(const Folder& from) {
    CopyFrom(from);
    return *this;
  }
  inline Folder& operator=(Folder&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Folder& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Folder* internal_default_instance() {
    return reinterpret_cast<const Folder*>(
               &_Folder_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Folder& a, Folder& b) {
    a.Swap(&b);
  }
  inline void Swap(Folder* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Folder* New() const final {
    return CreateMaybeMessage<Folder>(nullptr);
  }

  Folder* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Folder>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Folder& from);
  void MergeFrom(const Folder& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Folder* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "scribe.Folder";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Scribe_2eproto);
    return ::descriptor_table_Scribe_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldsFieldNumber = 8,
    kMailFieldNumber = 9,
    kReadPermFieldNumber = 1,
    kWritePermFieldNumber = 2,
    kSortFieldFieldNumber = 3,
    kUnreadCountFieldNumber = 4,
    kItemTypeFieldNumber = 5,
    kExpandedFieldNumber = 6,
    kThreadViewFieldNumber = 7,
  };
  // repeated .scribe.Field fields = 8;
  int fields_size() const;
  void clear_fields();
  ::scribe::Field* mutable_fields(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Field >*
      mutable_fields();
  const ::scribe::Field& fields(int index) const;
  ::scribe::Field* add_fields();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Field >&
      fields() const;

  // repeated .scribe.Email mail = 9;
  int mail_size() const;
  void clear_mail();
  ::scribe::Email* mutable_mail(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Email >*
      mutable_mail();
  const ::scribe::Email& mail(int index) const;
  ::scribe::Email* add_mail();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Email >&
      mail() const;

  // int32 readPerm = 1;
  void clear_readperm();
  ::PROTOBUF_NAMESPACE_ID::int32 readperm() const;
  void set_readperm(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 writePerm = 2;
  void clear_writeperm();
  ::PROTOBUF_NAMESPACE_ID::int32 writeperm() const;
  void set_writeperm(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 sortField = 3;
  void clear_sortfield();
  ::PROTOBUF_NAMESPACE_ID::int32 sortfield() const;
  void set_sortfield(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 unreadCount = 4;
  void clear_unreadcount();
  ::PROTOBUF_NAMESPACE_ID::int32 unreadcount() const;
  void set_unreadcount(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 itemType = 5;
  void clear_itemtype();
  ::PROTOBUF_NAMESPACE_ID::int32 itemtype() const;
  void set_itemtype(::PROTOBUF_NAMESPACE_ID::int32 value);

  // bool expanded = 6;
  void clear_expanded();
  bool expanded() const;
  void set_expanded(bool value);

  // bool threadView = 7;
  void clear_threadview();
  bool threadview() const;
  void set_threadview(bool value);

  // @@protoc_insertion_point(class_scope:scribe.Folder)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Field > fields_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Email > mail_;
  ::PROTOBUF_NAMESPACE_ID::int32 readperm_;
  ::PROTOBUF_NAMESPACE_ID::int32 writeperm_;
  ::PROTOBUF_NAMESPACE_ID::int32 sortfield_;
  ::PROTOBUF_NAMESPACE_ID::int32 unreadcount_;
  ::PROTOBUF_NAMESPACE_ID::int32 itemtype_;
  bool expanded_;
  bool threadview_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Scribe_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Field

// int32 id = 1;
inline void Field::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Field::id() const {
  // @@protoc_insertion_point(field_get:scribe.Field.id)
  return id_;
}
inline void Field::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:scribe.Field.id)
}

// int32 width = 2;
inline void Field::clear_width() {
  width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Field::width() const {
  // @@protoc_insertion_point(field_get:scribe.Field.width)
  return width_;
}
inline void Field::set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:scribe.Field.width)
}

// -------------------------------------------------------------------

// Address

// string name = 1;
inline void Address::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Address::name() const {
  // @@protoc_insertion_point(field_get:scribe.Address.name)
  return name_.GetNoArena();
}
inline void Address::set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Address.name)
}
inline void Address::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Address.name)
}
inline void Address::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Address.name)
}
inline void Address::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Address.name)
}
inline std::string* Address::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Address.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Address::release_name() {
  // @@protoc_insertion_point(field_release:scribe.Address.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Address::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:scribe.Address.name)
}

// string email = 2;
inline void Address::clear_email() {
  email_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Address::email() const {
  // @@protoc_insertion_point(field_get:scribe.Address.email)
  return email_.GetNoArena();
}
inline void Address::set_email(const std::string& value) {
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Address.email)
}
inline void Address::set_email(std::string&& value) {
  
  email_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Address.email)
}
inline void Address::set_email(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Address.email)
}
inline void Address::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Address.email)
}
inline std::string* Address::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Address.email)
  return email_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Address::release_email() {
  // @@protoc_insertion_point(field_release:scribe.Address.email)
  
  return email_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Address::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:scribe.Address.email)
}

// -------------------------------------------------------------------

// Email

// uint32 uid = 1;
inline void Email::clear_uid() {
  uid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Email::uid() const {
  // @@protoc_insertion_point(field_get:scribe.Email.uid)
  return uid_;
}
inline void Email::set_uid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.uid)
}

// int32 remoteFlags = 2;
inline void Email::clear_remoteflags() {
  remoteflags_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Email::remoteflags() const {
  // @@protoc_insertion_point(field_get:scribe.Email.remoteFlags)
  return remoteflags_;
}
inline void Email::set_remoteflags(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  remoteflags_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.remoteFlags)
}

// int32 localFlags = 3;
inline void Email::clear_localflags() {
  localflags_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Email::localflags() const {
  // @@protoc_insertion_point(field_get:scribe.Email.localFlags)
  return localflags_;
}
inline void Email::set_localflags(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  localflags_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.localFlags)
}

// int64 dateSent = 4;
inline void Email::clear_datesent() {
  datesent_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Email::datesent() const {
  // @@protoc_insertion_point(field_get:scribe.Email.dateSent)
  return datesent_;
}
inline void Email::set_datesent(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  datesent_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.dateSent)
}

// int64 dateReceived = 5;
inline void Email::clear_datereceived() {
  datereceived_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Email::datereceived() const {
  // @@protoc_insertion_point(field_get:scribe.Email.dateReceived)
  return datereceived_;
}
inline void Email::set_datereceived(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  datereceived_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.dateReceived)
}

// string label = 6;
inline void Email::clear_label() {
  label_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Email::label() const {
  // @@protoc_insertion_point(field_get:scribe.Email.label)
  return label_.GetNoArena();
}
inline void Email::set_label(const std::string& value) {
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Email.label)
}
inline void Email::set_label(std::string&& value) {
  
  label_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Email.label)
}
inline void Email::set_label(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Email.label)
}
inline void Email::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Email.label)
}
inline std::string* Email::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Email.label)
  return label_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Email::release_label() {
  // @@protoc_insertion_point(field_release:scribe.Email.label)
  
  return label_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.label)
}

// string subject = 7;
inline void Email::clear_subject() {
  subject_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Email::subject() const {
  // @@protoc_insertion_point(field_get:scribe.Email.subject)
  return subject_.GetNoArena();
}
inline void Email::set_subject(const std::string& value) {
  
  subject_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Email.subject)
}
inline void Email::set_subject(std::string&& value) {
  
  subject_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Email.subject)
}
inline void Email::set_subject(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  subject_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Email.subject)
}
inline void Email::set_subject(const char* value, size_t size) {
  
  subject_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Email.subject)
}
inline std::string* Email::mutable_subject() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Email.subject)
  return subject_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Email::release_subject() {
  // @@protoc_insertion_point(field_release:scribe.Email.subject)
  
  return subject_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_subject(std::string* subject) {
  if (subject != nullptr) {
    
  } else {
    
  }
  subject_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), subject);
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.subject)
}

// .scribe.Address from = 8;
inline bool Email::has_from() const {
  return this != internal_default_instance() && from_ != nullptr;
}
inline void Email::clear_from() {
  if (GetArenaNoVirtual() == nullptr && from_ != nullptr) {
    delete from_;
  }
  from_ = nullptr;
}
inline const ::scribe::Address& Email::from() const {
  const ::scribe::Address* p = from_;
  // @@protoc_insertion_point(field_get:scribe.Email.from)
  return p != nullptr ? *p : *reinterpret_cast<const ::scribe::Address*>(
      &::scribe::_Address_default_instance_);
}
inline ::scribe::Address* Email::release_from() {
  // @@protoc_insertion_point(field_release:scribe.Email.from)
  
  ::scribe::Address* temp = from_;
  from_ = nullptr;
  return temp;
}
inline ::scribe::Address* Email::mutable_from() {
  
  if (from_ == nullptr) {
    auto* p = CreateMaybeMessage<::scribe::Address>(GetArenaNoVirtual());
    from_ = p;
  }
  // @@protoc_insertion_point(field_mutable:scribe.Email.from)
  return from_;
}
inline void Email::set_allocated_from(::scribe::Address* from) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete from_;
  }
  if (from) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      from = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, from, submessage_arena);
    }
    
  } else {
    
  }
  from_ = from;
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.from)
}

// .scribe.Address reply = 9;
inline bool Email::has_reply() const {
  return this != internal_default_instance() && reply_ != nullptr;
}
inline void Email::clear_reply() {
  if (GetArenaNoVirtual() == nullptr && reply_ != nullptr) {
    delete reply_;
  }
  reply_ = nullptr;
}
inline const ::scribe::Address& Email::reply() const {
  const ::scribe::Address* p = reply_;
  // @@protoc_insertion_point(field_get:scribe.Email.reply)
  return p != nullptr ? *p : *reinterpret_cast<const ::scribe::Address*>(
      &::scribe::_Address_default_instance_);
}
inline ::scribe::Address* Email::release_reply() {
  // @@protoc_insertion_point(field_release:scribe.Email.reply)
  
  ::scribe::Address* temp = reply_;
  reply_ = nullptr;
  return temp;
}
inline ::scribe::Address* Email::mutable_reply() {
  
  if (reply_ == nullptr) {
    auto* p = CreateMaybeMessage<::scribe::Address>(GetArenaNoVirtual());
    reply_ = p;
  }
  // @@protoc_insertion_point(field_mutable:scribe.Email.reply)
  return reply_;
}
inline void Email::set_allocated_reply(::scribe::Address* reply) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reply_;
  }
  if (reply) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      reply = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reply, submessage_arena);
    }
    
  } else {
    
  }
  reply_ = reply;
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.reply)
}

// repeated .scribe.Address to = 10;
inline int Email::to_size() const {
  return to_.size();
}
inline void Email::clear_to() {
  to_.Clear();
}
inline ::scribe::Address* Email::mutable_to(int index) {
  // @@protoc_insertion_point(field_mutable:scribe.Email.to)
  return to_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Address >*
Email::mutable_to() {
  // @@protoc_insertion_point(field_mutable_list:scribe.Email.to)
  return &to_;
}
inline const ::scribe::Address& Email::to(int index) const {
  // @@protoc_insertion_point(field_get:scribe.Email.to)
  return to_.Get(index);
}
inline ::scribe::Address* Email::add_to() {
  // @@protoc_insertion_point(field_add:scribe.Email.to)
  return to_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Address >&
Email::to() const {
  // @@protoc_insertion_point(field_list:scribe.Email.to)
  return to_;
}

// uint32 colour = 11;
inline void Email::clear_colour() {
  colour_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Email::colour() const {
  // @@protoc_insertion_point(field_get:scribe.Email.colour)
  return colour_;
}
inline void Email::set_colour(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  colour_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.colour)
}

// int64 size = 12;
inline void Email::clear_size() {
  size_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Email::size() const {
  // @@protoc_insertion_point(field_get:scribe.Email.size)
  return size_;
}
inline void Email::set_size(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.size)
}

// string fileName = 13;
inline void Email::clear_filename() {
  filename_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Email::filename() const {
  // @@protoc_insertion_point(field_get:scribe.Email.fileName)
  return filename_.GetNoArena();
}
inline void Email::set_filename(const std::string& value) {
  
  filename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Email.fileName)
}
inline void Email::set_filename(std::string&& value) {
  
  filename_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Email.fileName)
}
inline void Email::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Email.fileName)
}
inline void Email::set_filename(const char* value, size_t size) {
  
  filename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Email.fileName)
}
inline std::string* Email::mutable_filename() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Email.fileName)
  return filename_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Email::release_filename() {
  // @@protoc_insertion_point(field_release:scribe.Email.fileName)
  
  return filename_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.fileName)
}

// int32 priority = 14;
inline void Email::clear_priority() {
  priority_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Email::priority() const {
  // @@protoc_insertion_point(field_get:scribe.Email.priority)
  return priority_;
}
inline void Email::set_priority(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  priority_ = value;
  // @@protoc_insertion_point(field_set:scribe.Email.priority)
}

// string structure = 15;
inline void Email::clear_structure() {
  structure_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Email::structure() const {
  // @@protoc_insertion_point(field_get:scribe.Email.structure)
  return structure_.GetNoArena();
}
inline void Email::set_structure(const std::string& value) {
  
  structure_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Email.structure)
}
inline void Email::set_structure(std::string&& value) {
  
  structure_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Email.structure)
}
inline void Email::set_structure(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  structure_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Email.structure)
}
inline void Email::set_structure(const char* value, size_t size) {
  
  structure_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Email.structure)
}
inline std::string* Email::mutable_structure() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Email.structure)
  return structure_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Email::release_structure() {
  // @@protoc_insertion_point(field_release:scribe.Email.structure)
  
  return structure_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_structure(std::string* structure) {
  if (structure != nullptr) {
    
  } else {
    
  }
  structure_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), structure);
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.structure)
}

// string messageId = 16;
inline void Email::clear_messageid() {
  messageid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Email::messageid() const {
  // @@protoc_insertion_point(field_get:scribe.Email.messageId)
  return messageid_.GetNoArena();
}
inline void Email::set_messageid(const std::string& value) {
  
  messageid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:scribe.Email.messageId)
}
inline void Email::set_messageid(std::string&& value) {
  
  messageid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:scribe.Email.messageId)
}
inline void Email::set_messageid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  messageid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:scribe.Email.messageId)
}
inline void Email::set_messageid(const char* value, size_t size) {
  
  messageid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:scribe.Email.messageId)
}
inline std::string* Email::mutable_messageid() {
  
  // @@protoc_insertion_point(field_mutable:scribe.Email.messageId)
  return messageid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Email::release_messageid() {
  // @@protoc_insertion_point(field_release:scribe.Email.messageId)
  
  return messageid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Email::set_allocated_messageid(std::string* messageid) {
  if (messageid != nullptr) {
    
  } else {
    
  }
  messageid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), messageid);
  // @@protoc_insertion_point(field_set_allocated:scribe.Email.messageId)
}

// -------------------------------------------------------------------

// Folder

// int32 readPerm = 1;
inline void Folder::clear_readperm() {
  readperm_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Folder::readperm() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.readPerm)
  return readperm_;
}
inline void Folder::set_readperm(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  readperm_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.readPerm)
}

// int32 writePerm = 2;
inline void Folder::clear_writeperm() {
  writeperm_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Folder::writeperm() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.writePerm)
  return writeperm_;
}
inline void Folder::set_writeperm(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  writeperm_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.writePerm)
}

// int32 sortField = 3;
inline void Folder::clear_sortfield() {
  sortfield_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Folder::sortfield() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.sortField)
  return sortfield_;
}
inline void Folder::set_sortfield(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sortfield_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.sortField)
}

// int32 unreadCount = 4;
inline void Folder::clear_unreadcount() {
  unreadcount_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Folder::unreadcount() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.unreadCount)
  return unreadcount_;
}
inline void Folder::set_unreadcount(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  unreadcount_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.unreadCount)
}

// int32 itemType = 5;
inline void Folder::clear_itemtype() {
  itemtype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Folder::itemtype() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.itemType)
  return itemtype_;
}
inline void Folder::set_itemtype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  itemtype_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.itemType)
}

// bool expanded = 6;
inline void Folder::clear_expanded() {
  expanded_ = false;
}
inline bool Folder::expanded() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.expanded)
  return expanded_;
}
inline void Folder::set_expanded(bool value) {
  
  expanded_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.expanded)
}

// bool threadView = 7;
inline void Folder::clear_threadview() {
  threadview_ = false;
}
inline bool Folder::threadview() const {
  // @@protoc_insertion_point(field_get:scribe.Folder.threadView)
  return threadview_;
}
inline void Folder::set_threadview(bool value) {
  
  threadview_ = value;
  // @@protoc_insertion_point(field_set:scribe.Folder.threadView)
}

// repeated .scribe.Field fields = 8;
inline int Folder::fields_size() const {
  return fields_.size();
}
inline void Folder::clear_fields() {
  fields_.Clear();
}
inline ::scribe::Field* Folder::mutable_fields(int index) {
  // @@protoc_insertion_point(field_mutable:scribe.Folder.fields)
  return fields_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Field >*
Folder::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_list:scribe.Folder.fields)
  return &fields_;
}
inline const ::scribe::Field& Folder::fields(int index) const {
  // @@protoc_insertion_point(field_get:scribe.Folder.fields)
  return fields_.Get(index);
}
inline ::scribe::Field* Folder::add_fields() {
  // @@protoc_insertion_point(field_add:scribe.Folder.fields)
  return fields_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Field >&
Folder::fields() const {
  // @@protoc_insertion_point(field_list:scribe.Folder.fields)
  return fields_;
}

// repeated .scribe.Email mail = 9;
inline int Folder::mail_size() const {
  return mail_.size();
}
inline void Folder::clear_mail() {
  mail_.Clear();
}
inline ::scribe::Email* Folder::mutable_mail(int index) {
  // @@protoc_insertion_point(field_mutable:scribe.Folder.mail)
  return mail_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Email >*
Folder::mutable_mail() {
  // @@protoc_insertion_point(field_mutable_list:scribe.Folder.mail)
  return &mail_;
}
inline const ::scribe::Email& Folder::mail(int index) const {
  // @@protoc_insertion_point(field_get:scribe.Folder.mail)
  return mail_.Get(index);
}
inline ::scribe::Email* Folder::add_mail() {
  // @@protoc_insertion_point(field_add:scribe.Folder.mail)
  return mail_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::scribe::Email >&
Folder::mail() const {
  // @@protoc_insertion_point(field_list:scribe.Folder.mail)
  return mail_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace scribe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Scribe_2eproto
